version: "3.8"

services:
  app:
    container_name: finance-api
    working_dir: /code
    volumes:
      - ./api:/code
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: p4ssw0rd
      MYSQL_DB: finance_db
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}

  db:
    image: mysql:8.0
    container_name: finance-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd
      MYSQL_DATABASE: finance_db
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
